language:
  - ruby
  - node_js
cache: bundler
install:
  - gem install bundler
  - gem install rails
env:
  global:
    MYSQL_USERNAME='root'
    MYSQL_HOST='127.0.0.1'
    MYSQL_SOCKET='~travis/.my.cnf'
rvm:
  - 2.5.1
servises:
  - mysql
scripts:
  - bundle install && yarn install
  - bundle exec rails db:create
  - bundle exec rails db:migrate
  - bundle exec rspec --color --require spec_helper --format progress spec
  - bundle exec rubocop
  - bin/webpack-dev-server

# bundle install をキャッシュ
# see: http://bekkou68.hatenablog.com/entry/2014/04/02/210754
